### ISSUE TITLE
Deliver result back as list or dataframe in sg_classifier.show_models()

### ISSUE THREAD

**Issue by bm765** [rebelosa/random-subgroups#1]
Hi,

thanks for bringing this library to the community.

Presently I am looking at `sg_classifier.show_models()`.

As in `pysubgroup`, I would like to get the results of the discovery back in a structure that I can work with in my own code.

Presently, only a `print` to the console is done in `show_models()`.

It would be nice and convenient if I could get back the results in a structured way (like in the package `pysubgroup`: a `list` or a `pandas.DataFrame`).

Thanks for considering this.

**Comment by rebelosa** [comment]
Hi

That was indeed a good suggestion! I just added that feature.

Feel free to propose any changes or make Pull Requests for new features.

Regards
